import {
  LayoutDashboard,
  TrendingUp,
  TrendingDown,
  Tag,
  FileText,
  Layers,
  CreditCard,
  Target,
  BarChart3,
  History,
  Trash2,
  Settings,
  Wallet,
  Home,
  ShoppingCart,
  Lightbulb,
  Car,
  HeartPulse,
  GraduationCap,
  Gamepad2,
  ShoppingBag,
  Sparkles,
  PawPrint,
  Users,
  Plane,
  Repeat,
  Receipt,
  Wrench,
  HelpCircle,
  Gift,
  Landmark,
  Building2,
  Briefcase,
  RotateCcw,
  RefreshCcw,
  PlusCircle,
  Award,
  Upload,
} from 'lucide-react';

export const ICONES_NAV = {
  LayoutDashboard,
  TrendingUp,
  TrendingDown,
  Tag,
  FileText,
  Layers,
  CreditCard,
  Target,
  BarChart3,
  History,
  Trash2,
  Settings,
  Wallet,
  Receipt,
  Upload,
};

// Ícone de cada categoria fixa (gasto e entrada) — usado no lugar do
// emoji, tanto nas listas quanto ao lado do select nos formulários
// (o <select> nativo do navegador não permite ícones dentro das
// opções, só texto puro).
export const ICONES_CATEGORIA_GASTO = {
  Alimentação: ShoppingCart,
  Assinaturas: Repeat,
  'Cartão de Crédito': CreditCard,
  Compras: ShoppingBag,
  'Contas da Casa': Lightbulb,
  'Cuidados Pessoais': Sparkles,
  Educação: GraduationCap,
  Família: Users,
  'Impostos e Taxas': Receipt,
  Investimentos: TrendingUp,
  Lazer: Gamepad2,
  Manutenção: Wrench,
  Moradia: Home,
  Outros: HelpCircle,
  Pets: PawPrint,
  Presentes: Gift,
  Saúde: HeartPulse,
  'Tarifas Bancárias': Landmark,
  Transporte: Car,
  Viagens: Plane,
};

export const ICONES_CATEGORIA_ENTRADA = {
  'Aluguel Recebido': Building2,
  Benefícios: Award,
  Estorno: RefreshCcw,
  Freelance: Briefcase,
  'Outras Entradas': HelpCircle,
  'Presentes Recebidos': Gift,
  Reembolso: RotateCcw,
  'Renda Extra': PlusCircle,
  'Rendimentos de Investimentos': TrendingUp,
  Salário: Wallet,
  'Venda de Produtos/Bens': ShoppingBag,
};

// Ícones que a pessoa pode escolher ao criar uma categoria própria —
// reaproveita os mesmos ícones já usados nas categorias fixas (sem
// precisar importar nada novo), com "Tag" como opção genérica.
export const ICONES_DISPONIVEIS = {
  Tag,
  ShoppingCart,
  Repeat,
  CreditCard,
  ShoppingBag,
  Lightbulb,
  Sparkles,
  GraduationCap,
  Users,
  Receipt,
  TrendingUp,
  Gamepad2,
  Wrench,
  Home,
  PawPrint,
  Gift,
  HeartPulse,
  Landmark,
  Car,
  Plane,
  Building2,
  Award,
  RefreshCcw,
  Briefcase,
  HelpCircle,
  RotateCcw,
  PlusCircle,
  Wallet,
};
